Feature: Public CLI help
  Global help should expose only commands intended for direct user control.

  Scenario: Global help presents the complete public command tree
    When I run the command "--help"
    Then the command succeeds
    And stdout contains "brightness get"
    And stdout contains "brightness set <0-100>"
    And stdout contains "volume <0-100>"
    And stdout contains "volume up"
    And stdout contains "volume down"
    And stdout contains "volume mute"
    And stdout contains "volume mute on"
    And stdout contains "volume mute off"
    And stdout contains "power on"
    And stdout contains "power off"
    And stdout contains "screen off"
    And stdout contains "screen on"
    And stdout contains "settings list"
    And stdout contains "settings describe [KEY]"
    And stdout contains "settings get <KEY>"
    And stdout contains "settings set <KEY> <VALUE>"
    And stdout contains "settings unset <KEY>"
    And stdout contains "updates check [--notify]"
    And stdout contains "updates install"
    And stdout contains "help [COMMAND...]"
    And stdout contains "--help, -h"
    And stdout contains "--version, -V"
    And stdout does not contain "startup"
    And stdout does not contain "shutdown"
    And stdout does not contain "sleep-pre"
    And stdout does not contain "  sleep "
    And stdout does not contain "nm-pre-down"
    And stdout does not contain "monitor"
    And stdout does not contain "lifecycle"
    And stdout does not contain "detect-backend"
    And stdout does not contain "screen-off"
    And stdout does not contain "screen-on"
    And stdout does not contain "updates background-check"
    And stdout does not contain "  dev "
    And stdout does not contain "webos-auth-probe"

  Scenario: Volume help is available at the scoped command level
    When I run the command "volume --help"
    Then the command succeeds
    And stdout contains "volume <0-100>"
    And stdout contains "volume up"
    And stdout contains "volume down"
    And stdout contains "volume mute"
    And stdout contains "volume mute on"
    And stdout contains "volume mute off"
    And stdout does not contain "volume set"
